openapi: '3.0.2'
info:
  title: 매장 API (매장관리)
  version: '1.0'
  contact:
    name: Code States
    url: https://codestates.com
  license:
    name: CC BY-NC
    url: https://creativecommons.org/licenses/?lang=ko
servers:
  - url: https://api.server.test/v1
  - url: https://api.chanhoe.click
  - url: https://server.yyuni.click
  - url: http://loadbalancer-service-1005947985.ap-northeast-2.elb.amazonaws.com

paths:
  /api/restaurant:
    get:
      description: '우리 매장 정보를 조회합니다'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/restaurant'
    patch:
      description: '우리 매장 정보를 수정합니다'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/restaurantPayload'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/restaurant'
  /api/menu:
    post:
      description: '메뉴를 추가합니다'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/menuPayload'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/menu'
  /api/menu/{id}:
    put:
      description: '특정 메뉴를 변경합니다'
      parameters: 
      - in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/menuPayload'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/menu'
    delete:
      description: '특정 메뉴를 삭제합니다'
      parameters: 
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '204':
          description: OK

components:
  schemas:
    restaurant:
      type: object
      properties:
        _id:
          type: string
          example: 62374c64e5bfa293bf21831b
        name:
          type: string
          example: 동백커피 센텀점
        menu:
          type: array
          items:
            $ref: '#/components/schemas/menu'
        address:
          type: string
          example: 부산시 수영구 센텀1로 777
        rating:
          type: number
          example: 4.8
    restaurantPayload:
      type: object
      properties:
        name:
          type: string
          example: 동백커피 센텀점
        address:
          type: string
          example: 부산시 수영구 센텀1로 777
    menu:
      type: object
      properties:
        _id:
          type: string
          example: 62374fe0e5bfa293bf218347
        name:
          type: string
          example: 동백커피
        price:
          type: number
          example: 4000
    menuPayload:
      type: object
      properties:
        name:
          type: string
          example: 동백커피
        price:
          type: number
          example: 4000